### ISSUE TITLE
TemplateSigner Class is missing Label property

### ISSUE THREAD

**Issue by goome126** [box/box-dotnet-sdk-gen#217]
- [✅] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [✅] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [✅] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference). 
- https://community.box.com/box-sign-api-9/box-sign-api-template-signers-do-not-include-label-field-in-sdk-s-2891 (My post)
- [✅] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The TemplateSigner class inside of Box.Sdk.Gen.Schemas does not contain the string field "Label". However, this field is available on the returned Sign Templates objects inside the Signers object array when calling the box api via http at these endpoints (https://api.box.com/2.0/sign_templates or /sign_templates/{template_id}). This is a problem because I'd like to be able to access this property inside of the .NET SDK, but currently it's unavailable.  

### Steps to Reproduce
After the creation of a box client and calling BoxClient.SignTemplates.GetSignTemplatesAsync() the returned SignTemplates object possesses a TemplateSigner object that does not have an accessible Label property.

### Expected Behavior
The expected behavior is for the TemplateSigner object to possess a Label property.

### Error Message, Including Stack Trace
N/A
### Screenshots
The result returned from https://api.box.com/2.0/sign_templates
![The result returned from https://api.box.com/2.0/sign_templates](https://github.com/user-attachments/assets/9aea20b7-4f70-4a5e-b937-34df5bf0f581)

The .NET SDK Sign Template class represented as JSON
![The .NET SDK Sign Template class represented as JSON](https://github.com/user-attachments/assets/5690c6f8-f997-4774-aefd-93a1c93138cc)

### Versions Used

.NET SDK: 8
.NET: 8.0.7

[sdk-docs]: https://github.com/box/box-dotnet-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-dotnet-sdk-gen/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @goome126, 
thanks for reaching us. box-dotnet-sdk-gen is generated based on API specification. Unfortunately this field is missing in our spec ([here](https://developer.box.com/reference/resources/sign-template/)). We will add missing field to the specification and regenerate SDK, then the field should show up.
Best,
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @goome126,
the fix has been released in 1.1.0 version.
Best,
@lukaszsocha2
