### ISSUE TITLE
SDK won't work on AWS Lambda environments (Bouncy Castle Module checksum failed)

### ISSUE THREAD

**Issue by luizhcrocha** [box/box-dotnet-sdk-gen#309]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
SDK won't work on AWS Lambda environments, probably because of conflicts with Boucy Castle. 

Works fine locally, running on Windows 11. 

### Steps to Reproduce

Deploy a dotnet project to AWS Lambda using this:
```Dockerfile
# Base image
FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS base
WORKDIR /src

COPY ["Project.Lambda", "Project.Lambda/"]

WORKDIR "/src/Project.Lambda"

FROM base AS publish
RUN dotnet publish "Project.csproj" \
    -c Release \
    -r linux-x64 \
    --output ./bin/Release/lambda-publish \
    -p:WarningLevel=0 

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:8.0-jammy AS final
WORKDIR /var/task
COPY --from=publish /src/Project.Lambda/bin/Release/lambda-publish .
ENTRYPOINT ["dotnet", "exec", "/var/task/Project.Lambda.dll"]
```
```aws-lambda-tools-defaults.json
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "[region]",
  "configuration": "Release",
  "s3-prefix": "Project.Lambda/",
  "template": "serverless.template",
  "template-parameters": ""
}
```
```Project.Lambda.csproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>exe</OutputType>
        <AWSProjectType>Lambda</AWSProjectType>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PackageId>Project.Lambda</PackageId>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.11.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.CloudWatchEvents" Version="4.4.0"/>
        <PackageReference Include="Amazon.Lambda.Annotations" Version="1.5.3" />
        <PackageReference Include="Amazon.Lambda.Core" Version="2.4.0" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    </ItemGroup>
</Project>
```

### Expected Behavior

SDK should work. 

### Error Message, Including Stack Trace
On CloudWatch logs: 
> ---> Org.BouncyCastle.Pkcs.PkcsException: unable to read encrypted data: Module checksum failed: Module checksum failed: expected [813bafa530a2d43aac4b851216fd80cecc4b42249d2f438fca9229665ea2f8a6d4a9756a6a103e2f5d63fd2dcc8194b30a7f7b479d15525e3fe2e3d359ed93c4] got [9510306a254b96766dcc234ca1424f9f6fd9d188f49819324ef0094f6f76eea2fe830ea5c0bc82891834658c452ecfc7112577d8ac0d3f2fb9addb73f1262bc6]
--
  | 2024-11-11T21:09:02.607Z | ---> Org.BouncyCastle.Crypto.CryptoOperationError: Module checksum failed: Module checksum failed: expected [813bafa530a2d43aac4b851216fd80cecc4b42249d2f438fca9229665ea2f8a6d4a9756a6a103e2f5d63fd2dcc8194b30a7f7b479d15525e3fe2e3d359ed93c4] got [9510306a254b96766dcc234ca1424f9f6fd9d188f49819324ef0094f6f76eea2fe830ea5c0bc82891834658c452ecfc7112577d8ac0d3f2fb9addb73f1262bc6]
  | 2024-11-11T21:09:02.607Z | ---> Org.BouncyCastle.Crypto.CryptoOperationError: Module checksum failed: expected [813bafa530a2d43aac4b851216fd80cecc4b42249d2f438fca9229665ea2f8a6d4a9756a6a103e2f5d63fd2dcc8194b30a7f7b479d15525e3fe2e3d359ed93c4] got [9510306a254b96766dcc234ca1424f9f6fd9d188f49819324ef0094f6f76eea2fe830ea5c0bc82891834658c452ecfc7112577d8ac0d3f2fb9addb73f1262bc6]
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Crypto.CryptoStatus.MoveToErrorStatus(CryptoOperationError error)
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Crypto.CryptoStatus.ChecksumValidate()
  | 2024-11-11T21:09:02.607Z | --- End of inner exception stack trace ---
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Crypto.CryptoStatus.MoveToErrorStatus(CryptoOperationError error)
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Crypto.CryptoStatus.ChecksumValidate()
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Crypto.CryptoStatus.IsReady()
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Security.SecurityContext.CreateBuilder[A](IBuilderServiceType`1 type)
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Operators.PkixPbeDecryptorProviderBuilder.MyDecryptorBuilderProvider.CreateDecryptorBuilder(AlgorithmIdentifier algorithmDetails)
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Pkcs.Pkcs8EncryptedPrivateKeyInfo.DecryptPrivateKeyInfo(IDecryptorBuilderProvider`1 inputDecryptorProvider)
  | 2024-11-11T21:09:02.607Z | --- End of inner exception stack trace ---
  | 2024-11-11T21:09:02.607Z | at Org.BouncyCastle.Pkcs.Pkcs8EncryptedPrivateKeyInfo.DecryptPrivateKeyInfo(IDecryptorBuilderProvider`1 inputDecryptorProvider)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.Internal.JwtUtils.GetSigningCredentials(JwtKey key)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.Internal.JwtUtils.CreateJwtAssertion(Dictionary`2 claims, JwtKey key, JwtSignOptions options)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.BoxJwtAuth.RefreshTokenAsync(NetworkSession networkSession)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.BoxJwtAuth.RetrieveTokenAsync(NetworkSession networkSession)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.BoxJwtAuth.RetrieveAuthorizationHeaderAsync(NetworkSession networkSession)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.Internal.HttpClientAdapter.BuildHttpRequest(FetchOptions options, Stream stream)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.Internal.HttpClientAdapter.FetchAsync(FetchOptions options)
  | 2024-11-11T21:09:02.607Z | at Box.Sdk.Gen.Managers.UsersManager.GetUserMeAsync(GetUserMeQueryParams queryParams, GetUserMeHeaders headers, Nullable`1 cancellationToken)
  | 2024-11-11T21:09:02.607Z | at Box.Integration.Auth.GetBoxClientAsync(String secretName, String region) in /src/Box.Integration/Auth.cs:line 58

### Versions Used

.NET SDK: 8.0
.NET: 8.0

[sdk-docs]: https://github.com/box/box-dotnet-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-dotnet-sdk-gen/search?type=Issues

**Comment by congminh1254** [comment]
Hi @luizhcrocha 

Thanks for submitting this issue, we are investigating and will get back to you when have more input.

In the meantime, can you provide more detail of the project file, as I see there is no Box SDK Gen listed there.\

Bests,
Minh

**Comment by congminh1254** [comment]
Hi @luizhcrocha 

We are able to reproduce the issue, and investigating.

**Comment by congminh1254** [comment]
Hi @luizhcrocha 

This issue because of the BouncyCastle library doing the checksum before run, and in your lambda project is using the feature `PublishReadyToRun` so dotnet generate a new `dll` file but not the original one.

So please in your `.csproj` file, add these following lines to exclude specific assemblies from ReadyToRun processing:
```
<ItemGroup>
  <PublishReadyToRunExclude Include="bc-fips-1.0.2.dll" />
  <PublishReadyToRunExclude Include="bcpkix-fips-1.0.2.dll" />
</ItemGroup>
```

Let us know if it works.

Bests,
Minh

**Comment by luizhcrocha** [comment]
Thank you, @congminh1254. It worked. 🎉
