### ISSUE TITLE
Can ProxyConfig support DefaultNetworkCredentials ?

### ISSUE THREAD

**Issue by deleepgeorge** [box/box-dotnet-sdk-gen#333]
- [x ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### ProxyConfig and DefaultNetworkCredentials 

It appears that ProxyConfig currently only supports basic proxy authentication (username , password). Is there a way to pass DefaultNetworkCredentials while creating the proxy? or is there a roadmap to support DefaultNetworkCredentials in the future? I am unable to use this SDK at this time because of this limitation. 

**Reference :**
box-dotnet-sdk-gen/Box.Sdk.Gen/Networking/Fetch.cs > CreateProxyClient(.....)

### Versions Used

.NET SDK: 8.0

[sdk-docs]: https://github.com/box/box-dotnet-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-dotnet-sdk-gen/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi,
we will push the fix today.
Best,
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @deleepgeorge,
this feature is now available in v1.5.0 release.
Best,
@lukaszsocha2
